### PR TITLE
Add plugin refreshVersions

### PR DESCRIPTION
**Pull request by jmfayard**
See documentation at https://jmfayard.github.io/refreshVersions/

### CODE REVIEW

**Comment by pavlospt** [comment]
Hey @jmfayard , thank you for the PR 😄  Is this generated from the automated tool?

**Comment by jmfayard** [comment]
Ah ah ah, I wish we were so advanced, but no it's just me

**Comment by jmfayard** [comment]
The `versions.properties` is auto-generated and will come with available updates next time you run `./gradlew refreshVersions`

The rest is not

**Comment by pavlospt** [comment]
Cool, thank you for explaining! Will wait for CI to pass!

**Comment by jmfayard** [comment]
The CI doesn't seem to be working :)

**Comment by pavlospt** [comment]
@jmfayard Could you try `git commit --amend && git push -f` on your last commit so that it could be re-triggered?

**Comment by jmfayard** [comment]
@pavlospt it still doesn't run

**Comment by pavlospt** [comment]
@jmfayard hmmm give me some time to check this since I am not sure how this will be re-run. GAs do not offer manual trigger :/

**Pull request closed without merging**
